// pages/projects/index.vue
<script setup>
  import ProjectTypeSelector from '@/components/Project/ProjectTypeSelector'
  import ProjectList from '@/components/Project/ProjectList'
  import { login } from '@/services/auth'
  import { getTypes } from '@/services/type'
  import { getProjects } from '@/services/project'

  const authData = await login()

  let types    = []
  let projects = []

  if (authData?.token) {
    types = await getTypes(authData.token)
    projects = await getProjects(authData.token)
  }
</script>

<template>
  <ProjectTypeSelector :types="types" />
  <ProjectList :projects="projects" />
</template>

// pages/projects/index.tsx
import { getProjectListProps } from '../../app/lib/static-props';
import ProjectList from '../../app/components/Project/ProjectList';

export async function getStaticProps() {
  return {
    props: await getProjectListProps()
  }
}

const Projects = ({ types, projects }) => {
  return (
    <ProjectList
      types={ types }
      projects={ projects } />
  )
}

export default Projects;
